package:
  name: HappyNeuron
  version: '0.0.1'

source:
  git_url: https://github.com/ravescovi/HappyNeuron.git

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy

test:
  # Python imports
  imports:
    - happyneuron

about:
  license: BSD-3
  summary: 'Exascale pipeline for processing neural microscopy data.'
